=== coderunner4/icardea/icardea-consenteditor/src/main/resources/schemas/ConsentModel.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="model.consenteditor.srdc.com.tr" targetNamespace="model.consenteditor.srdc.com.tr"
	elementFormDefault="qualified" attributeFormDefault="qualified"
	xmlns:hj="http://hyperjaxb3.jvnet.org/ejb/schemas/customizations"
	xmlns:orm="http://java.sun.com/xml/ns/persistence/orm">
	<xsd:element name="actionElements">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="action" type="tns:non_empty_string"
					maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="patientId" type="tns:non_empty_string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="resourceElements">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:resourceElement" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="patientId" type="tns:non_empty_string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="subjectElements">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:subjectElement" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="patientId" type="tns:non_empty_string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="consentDocumentMetaDataType">
		<xsd:sequence>			
			<xsd:element name="patientId" type="tns:non_empty_string"
				minOccurs="0" />
			<xsd:element name="definition" type="tns:non_empty_string"
				minOccurs="0" />
			<xsd:element name="creationDate" type="tns:non_empty_string"
				minOccurs="0" />
			<xsd:element name="modificationDate" type="tns:non_empty_string"
				minOccurs="0" />
			<xsd:element name="expirationDate" type="tns:non_empty_string"
				minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="consentDocument">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="consentDocumentMetaData" type="tns:consentDocumentMetaDataType">
				</xsd:element>
				<xsd:element ref="tns:consentRule" maxOccurs="unbounded" />				
			</xsd:sequence>
			<xsd:attribute name="id" type="tns:non_empty_string">
				<xsd:annotation>
					<xsd:appinfo>
						<hj:id/>
					</xsd:appinfo>
				</xsd:annotation>							
			</xsd:attribute>
			<xsd:attribute name="isCurrent" type="tns:non_empty_string"
				use="required" />
		</xsd:complexType>
	</xsd:element>	
	<xsd:element name="consentRuleTarget">
		<xsd:complexType>
			<xsd:sequence>				
				<xsd:element ref="tns:subjectElements" />
				<xsd:element ref="tns:resourceElements" />
				<xsd:element ref="tns:actionElements" />				
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="consentRule">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="description" type="tns:non_empty_string" />
				<xsd:element ref="tns:consentRuleTarget"/>
				<xsd:element name="isAllow" type="xsd:int" default="2" />
				<xsd:element ref="tns:condition" minOccurs="0"
					maxOccurs="unbounded" />
				<xsd:element ref="tns:obligation" minOccurs="0" />
			</xsd:sequence>			
			<xsd:attribute name="id" type="tns:non_empty_string"
				use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="non_empty_string">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="condition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:timeConstraint" minOccurs="0" />
				<xsd:element name="inEmergency" type="xsd:boolean"
					minOccurs="0" />
				<xsd:element name="purpose" type="tns:non_empty_string"
					minOccurs="0" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="timeConstraint">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="allowFrom" type="tns:non_empty_string" />
				<xsd:element name="allowUntil" type="tns:non_empty_string" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="obligation">
		<xsd:complexType>
			<xsd:choice>
				<xsd:element ref="tns:sentEmailTo" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="sentEmailTo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="to" type="tns:emailAddress"
					maxOccurs="unbounded" />
				<xsd:element name="emailText" type="tns:non_empty_string" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="emailAddress">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[^@]+@[^\.]+\..+" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="subjectElement">
		<xsd:complexType>
			<xsd:choice>
				<xsd:element ref="tns:individual" />
				<xsd:element ref="tns:group" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="group">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="id" type="tns:non_empty_string" />
				<xsd:element name="name" type="tns:non_empty_string" />
				<xsd:element name="description" type="tns:non_empty_string"
					minOccurs="0" />
				<xsd:element ref="tns:members" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="isUserDefined" type="xsd:boolean"
				use="optional" default="false" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="members">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:individual" minOccurs="0"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="individual">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="id" type="tns:non_empty_string" />
				<xsd:element name="name" type="tns:non_empty_string"/>
				<xsd:element name="surname" type="tns:non_empty_string"/>
				<xsd:element name="role" type="tns:non_empty_string"
					minOccurs="0" maxOccurs="unbounded" />
<!--				<xsd:element name="type" type="tns:non_empty_string"-->
<!--					minOccurs="1" maxOccurs="1" />-->
<!--				<xsd:element name="speciality" type="tns:non_empty_string"-->
<!--					minOccurs="0" maxOccurs="unbounded" />-->
<!--				<xsd:element name="subjectIdentifier" type="tns:non_empty_string"-->
<!--					minOccurs="1" maxOccurs="1" />-->
<!--				<xsd:element name="organization" type="tns:non_empty_string"-->
<!--					minOccurs="0" maxOccurs="unbounded" />-->
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="resourceElement">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="id" type="tns:non_empty_string" />
				<xsd:element name="name" type="tns:non_empty_string" />
				<xsd:element name="confidentialityCode" type="tns:non_empty_string"
					minOccurs="0" />
<!--				<xsd:element name="resourcePath" type="tns:non_empty_string"-->
<!--					minOccurs="0" />-->
<!--				<xsd:element name="resourceIdentifier" type="tns:non_empty_string" />-->
<!--				<xsd:element name="sectionName" type="tns:non_empty_string"-->
<!--					minOccurs="0" />-->
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== coderunner4/icardea/trunk/icardea-consenteditor/src/main/resources/conf/resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<tns:resourceElements tns:patientId="default" xsi:schemaLocation="model.consenteditor.srdc.com.tr schemas\ConsentModel.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="model.consenteditor.srdc.com.tr">
    <tns:resourceElement>
        <tns:id>RESOURCECODE:ALLERGY</tns:id>
        <tns:name>Allergies</tns:name>        
        <tns:confidentialityCode>ALL</tns:confidentialityCode>        
    </tns:resourceElement>
    <tns:resourceElement>
        <tns:id>RESOURCECODE:CONDITION</tns:id>
        <tns:name>Conditions</tns:name>        
        <tns:confidentialityCode>ALL</tns:confidentialityCode>        
    </tns:resourceElement>
    <tns:resourceElement>
        <tns:id>RESOURCECODE:OPERATION</tns:id>
        <tns:name>Operations</tns:name>
        <tns:confidentialityCode>ALL</tns:confidentialityCode>
    </tns:resourceElement>
    <tns:resourceElement>
        <tns:id>RESOURCECODE:MEDICATION</tns:id>
        <tns:name>Medications</tns:name>        
        <tns:confidentialityCode>ALL</tns:confidentialityCode>
    </tns:resourceElement>
    <tns:resourceElement>
        <tns:id>RESOURCECODE:TESTRESULT</tns:id>
        <tns:name>Test Results</tns:name>        
        <tns:confidentialityCode>ALL</tns:confidentialityCode>
    </tns:resourceElement>
    <tns:resourceElement>
        <tns:id>RESOURCECODE:IMMUNIZATION</tns:id>
        <tns:name>Immunizations</tns:name>
        <tns:confidentialityCode>ALL</tns:confidentialityCode>
    </tns:resourceElement>
    <tns:resourceElement>
        <tns:id>RESOURCECODE:HOSPITALVISIT</tns:id>
        <tns:name>Hospital Visit</tns:name>
        <tns:confidentialityCode>ALL</tns:confidentialityCode>
    </tns:resourceElement>
    <tns:resourceElement>
        <tns:id>RESOURCECODE:BASICHEALTH</tns:id>
        <tns:name>Basic Health Information</tns:name>
        <tns:confidentialityCode>ALL</tns:confidentialityCode>
    </tns:resourceElement>
</tns:resourceElements>

=== coderunner4/icardea/trunk/icardea-consenteditor/src/main/resources/conf/consentDocuments/8c209e6c-e1db-45e9-9931-4d70dd2ef69e.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:consentDocument tns:isCurrent="0"
	tns:id="8c209e6c-e1db-45e9-9931-4d70dd2ef69e"
    xsi:schemaLocation="model.consenteditor.srdc.com.tr sampleData\ConsentModel.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="model.consenteditor.srdc.com.tr">
    <tns:consentDocumentMetaData>
    </tns:consentDocumentMetaData>
    <tns:consentRule tns:id="12132923489">
        <tns:description>Dentists can update my basic health information and conditions</tns:description>
        <tns:consentRuleTarget>
            <tns:subjectElements>
                <tns:subjectElement>
                    <tns:group tns:isUserDefined="false">
                        <tns:id>ROLECODE:DENTIST</tns:id>
                        <tns:name>Dentist</tns:name>
                        <tns:members />
                    </tns:group>
                </tns:subjectElement>
            </tns:subjectElements>
            <tns:resourceElements>
                <tns:resourceElement>
                    <tns:id>RESOURCECODE:BASICHEALTH</tns:id>
                    <tns:name>Basic Health Information</tns:name>
                    <tns:confidentialityCode>LOW</tns:confidentialityCode>
                </tns:resourceElement>
                <tns:resourceElement>
                    <tns:id>RESOURCECODE:CONDITION</tns:id>
                    <tns:name>Conditions</tns:name>
                    <tns:confidentialityCode>LOW</tns:confidentialityCode>
                </tns:resourceElement>
            </tns:resourceElements>
            <tns:actionElements>
                <tns:action>WRITE</tns:action>
            </tns:actionElements>
        </tns:consentRuleTarget>
        <tns:isAllow>1</tns:isAllow>
        <tns:condition>
            <tns:timeConstraint>
                <tns:allowFrom>2001-12-17 09:30:27</tns:allowFrom>
                <tns:allowUntil>2011-12-20 19:30:27</tns:allowUntil>
            </tns:timeConstraint>
        </tns:condition>
        <tns:obligation>
            <tns:sentEmailTo>
                <tns:to>hastamail@deneme.com.tr</tns:to>
                <tns:to>hastayakin@deneme.com.tr</tns:to>
                <tns:emailText>deneme bir iki</tns:emailText>
            </tns:sentEmailTo>
        </tns:obligation>
    </tns:consentRule>
    <tns:consentRule tns:id="dsfdsffdsfsfds">
        <tns:description>Doctors can read my test results and conditions, Pharmacists can read my medications and conditions.</tns:description>
        <tns:consentRuleTarget>
            <tns:subjectElements>
                <tns:subjectElement>
                    <tns:group tns:isUserDefined="false">
                        <tns:id>ROLECODE:PHARMACIST</tns:id>
                        <tns:name>Pharmacist</tns:name>
                        <tns:members />
                    </tns:group>
                </tns:subjectElement>
                <tns:subjectElement>
                    <tns:group tns:isUserDefined="false">
                        <tns:id>ROLECODE:DOCTOR</tns:id>
                        <tns:name>Doctor</tns:name>
                        <tns:description>Reseachers</tns:description>
                        <tns:members />
                    </tns:group>
                </tns:subjectElement>
            </tns:subjectElements>
            <tns:resourceElements>
                <tns:resourceElement>
                    <tns:id>RESOURCECODE:MEDICATION</tns:id>
                    <tns:name>Medications</tns:name>
                    <tns:confidentialityCode>ALL</tns:confidentialityCode>
                </tns:resourceElement>
                <tns:resourceElement>
                    <tns:id>RESOURCECODE:CONDITION</tns:id>
                    <tns:name>Conditions</tns:name>
                    <tns:confidentialityCode>ALL</tns:confidentialityCode>
                </tns:resourceElement>
            </tns:resourceElements>
            <tns:actionElements>
                <tns:action>READ</tns:action>
            </tns:actionElements>
        </tns:consentRuleTarget>
        <tns:isAllow>1</tns:isAllow>
        <tns:condition>
            <tns:timeConstraint>
                <tns:allowFrom>2001-12-17 09:30:27</tns:allowFrom>
                <tns:allowUntil>2011-12-20 19:30:27</tns:allowUntil>
            </tns:timeConstraint>
        </tns:condition>
        <tns:obligation>
            <tns:sentEmailTo>
                <tns:to>desee@deneme.com.tr</tns:to>
                <tns:emailText>deneme bir iki</tns:emailText>
            </tns:sentEmailTo>
        </tns:obligation>
    </tns:consentRule>
    <tns:consentRule tns:id="abnmkllhgllhgf">
        <tns:description>Nurses can not update my basic health information</tns:description>
        <tns:consentRuleTarget>
            <tns:subjectElements>
                <tns:subjectElement>
                    <tns:group tns:isUserDefined="false">
                        <tns:id>ROLECODE:NURSE</tns:id>
                        <tns:name>Nurse</tns:name>
                        <tns:members />
                    </tns:group>
                </tns:subjectElement>
            </tns:subjectElements>
            <tns:resourceElements>
                <tns:resourceElement>
                    <tns:id>RESOURCECODE:BASICHEALTH</tns:id>
                    <tns:name>Basic Health Information</tns:name>
                    <tns:confidentialityCode>LOW</tns:confidentialityCode>
                </tns:resourceElement>
            </tns:resourceElements>
            <tns:actionElements>
                <tns:action>UPDATE</tns:action>
            </tns:actionElements>
        </tns:consentRuleTarget>
        <tns:isAllow>0</tns:isAllow>
    </tns:consentRule>
    <tns:consentRule tns:id="12345678hnvdsad">
        <tns:description>Doctors can update my medications and operations</tns:description>
        <tns:consentRuleTarget>
            <tns:subjectElements>
                <tns:subjectElement>
                    <tns:group tns:isUserDefined="false">
                        <tns:id>ROLECODE:DOCTOR</tns:id>
                        <tns:name>Doctor</tns:name>
                        <tns:members />
                    </tns:group>
                </tns:subjectElement>
            </tns:subjectElements>
            <tns:resourceElements>
                <tns:resourceElement>
                    <tns:id>RESOURCECODE:OPERATION</tns:id>
                    <tns:name>Operations</tns:name>
                    <tns:confidentialityCode>ALL</tns:confidentialityCode>
                </tns:resourceElement>
                <tns:resourceElement>
                    <tns:id>RESOURCECODE:MEDICATION</tns:id>
                    <tns:name>Medications</tns:name>
                    <tns:confidentialityCode>ALL</tns:confidentialityCode>
                </tns:resourceElement>
            </tns:resourceElements>
            <tns:actionElements>
                <tns:action>READ</tns:action>
                <tns:action>UPDATE</tns:action>
            </tns:actionElements>
        </tns:consentRuleTarget>
        <tns:isAllow>1</tns:isAllow>
    </tns:consentRule>
</tns:consentDocument>
